version: '3'
services:
    ui:
        image: nginx
        volumes:
           - './ui:/usr/share/nginx/html'
           - '/app/node_modules'
        environment:
           - CHOKIDAR_USEPOLLING=true
        ports:
          - 3000:80

    api:
        build:
            context: api
        volumes:
            - "./api:/code"
        environment:
          - CHOKIDAR_USEPOLLING=true
          - PORT=5000 
        ports:
          - 5000:5000

    db:
        image: mongo
        volumes:
            - db:/data/db
            # after creating db volume
            # - "./dump:/dump"
        ports:
            - 27017:27017

volumes:
    db:
