version: '3'
services:
    ui:
        build:
            context: ui
            dockerfile: Dockerfile.prod 
        restart: on-failure:5
        networks:
            - traefik
        labels:
            # traefik config
           - "holten.publish=j"
           - "traefik.http.routers.ui-stud.rule=Host(`studentischerfilmclub.de`)"
           - "traefik.http.routers.ui-stud.tls.certResolver=letsencrypt"

    api:
        build:
            context: api
            dockerfile: Dockerfile.prod
        restart: on-failure:5
        networks:
            - traefik
        labels:
            # traefik config
           - "holten.publish=j"
           - "traefik.http.routers.api-stud.rule=Host(`studentischerfilmclub.de`) && PathPrefix(`/api/`)"
           - "traefik.http.routers.api-stud.tls.certResolver=letsencrypt"
           - "traefik.http.routers.api-stud.middlewares=strip-api-prefix@file"

    db:
        image: mongo
        volumes:
            - db:/data/db
            # after creating db volume
            # - "./dump:/dump"
        restart: on-failure:5
        networks:
            - traefik

networks:
    traefik:
        external: true

volumes:
    db:
