version: '3'
services:
    ui:
        build:
            context: ui
            dockerfile: Dockerfile.prod 
        restart: on-failure:5
        networks:
            - traefik
        labels:
            # traefik config
           - "holten.publish=j"
           #- "traefik.http.middlewares.asstr-basicauth.basicauth.users=joseph:$$2y$$05$$7r0v1BexW8Mfgo1wqzqxL.mr7eihQfdYKrEdJB0QY3TmU/6FixfqO"
           - "traefik.http.routers.webserver.rule=Host(`studentischerfilmclub.holten.com`)"
           - "traefik.http.routers.webserver.tls=true"
           #- "traefik.http.routers.webserver.middlewares=whitelistvpn@file,asstr-basicauth@docker"

    api:
        build:
            context: api
            dockerfile: Dockerfile.prod
        restart: on-failure:5
        networks:
            - traefik
        labels:
            # traefik config
           - "holten.publish=j"
           - "traefik.http.routers.webserver.rule=Host(`studentischerfilmclub.holten.com`) && PathPrefix(/api)"
           - "traefik.http.routers.webserver.tls=true"

    db:
        image: mongo
        volumes:
            - db:/data/db
            # after creating db volume
            # - "./dump:/dump"
        ports:
            - 27017:27017
        restart: on-failure:5
        networks:
            - traefik

networks:
    traefik:
        external: true

volumes:
    db:
